[package]
name = "rust-pokedex"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
chrono = "0.4.41"
datetime = "0.5.2"
rand = "0.9.1"
reqwest = {version = "0.12.19", features = ["blocking"]}
serde = {version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
